#!/bin/bash

# https://www.golinuxcloud.com/get-script-name-get-script-path-shell-script/#Get_script_path_in_shell_script

DOCKER_COMPOSE=$(dirname $(readlink -f "$0"))/docker-compose.yml

docker-compose -f "$DOCKER_COMPOSE" up
docker-compose -f "$DOCKER_COMPOSE" down
